CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Description" text,
        "ParentCategoryId" integer,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categories_Categories_ParentCategoryId" FOREIGN KEY ("ParentCategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(255) NOT NULL,
        "PasswordHash" character varying(255) NOT NULL,
        "FirstName" character varying(100) NOT NULL,
        "LastName" character varying(100) NOT NULL,
        "Role" integer NOT NULL,
        "ProfilePictureUrl" character varying(500),
        "IsBlocked" boolean NOT NULL,
        "Bio" text,
        "Specialization" character varying(200),
        "YearsOfExperience" integer,
        "Thesis" bytea,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Courses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(200) NOT NULL,
        "Description" text,
        "CoverImageUrl" character varying(500),
        "Price" numeric(10,2) NOT NULL,
        "Status" integer NOT NULL,
        "LecturerId" integer NOT NULL,
        "CategoryId" integer NOT NULL,
        "PublishedAt" timestamp with time zone,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Courses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Courses_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Courses_Users_LecturerId" FOREIGN KEY ("LecturerId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Enrollments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StudentId" integer NOT NULL,
        "CourseId" integer NOT NULL,
        "EnrolledAt" timestamp with time zone NOT NULL,
        "ProgressPercent" numeric(5,2) NOT NULL,
        "IsCompleted" boolean NOT NULL,
        "CompletedAt" timestamp with time zone,
        "LastAccessedAt" timestamp with time zone,
        CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Enrollments_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Enrollments_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Modules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CourseId" integer NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" text,
        "OrderIndex" integer NOT NULL,
        CONSTRAINT "PK_Modules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Modules_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Reviews" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StudentId" integer NOT NULL,
        "CourseId" integer NOT NULL,
        "Rating" integer NOT NULL,
        "Comment" text,
        "IsDeleted" boolean NOT NULL,
        "DeletedAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reviews_Courses_CourseId" FOREIGN KEY ("CourseId") REFERENCES "Courses" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reviews_Users_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Certificates" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EnrollmentId" integer NOT NULL,
        "CertificateNumber" character varying(100) NOT NULL,
        "IssuedAt" timestamp with time zone NOT NULL,
        "CertificateUrl" character varying(500),
        "VerificationCode" character varying(50) NOT NULL,
        CONSTRAINT "PK_Certificates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Certificates_Enrollments_EnrollmentId" FOREIGN KEY ("EnrollmentId") REFERENCES "Enrollments" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Payments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EnrollmentId" integer NOT NULL,
        "Amount" numeric(10,2) NOT NULL,
        "Currency" character varying(10) NOT NULL,
        "PaymentMethod" character varying(50),
        "TransactionId" character varying(100),
        "Status" integer NOT NULL,
        "PaidAt" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Payments_Enrollments_EnrollmentId" FOREIGN KEY ("EnrollmentId") REFERENCES "Enrollments" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Lectures" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ModuleId" integer NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" text,
        "OrderIndex" integer NOT NULL,
        "VideoUrl" character varying(500),
        "DocumentUrl" character varying(500),
        "DurationMinutes" integer,
        CONSTRAINT "PK_Lectures" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Lectures_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Quizzes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ModuleId" integer NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" text,
        "PassingScore" integer NOT NULL,
        "OrderIndex" integer NOT NULL,
        CONSTRAINT "PK_Quizzes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Quizzes_Modules_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Modules" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "LectureProgresses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EnrollmentId" integer NOT NULL,
        "LectureId" integer NOT NULL,
        "IsCompleted" boolean NOT NULL,
        "CompletedAt" timestamp with time zone,
        "WatchTimeSeconds" integer NOT NULL,
        CONSTRAINT "PK_LectureProgresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LectureProgresses_Enrollments_EnrollmentId" FOREIGN KEY ("EnrollmentId") REFERENCES "Enrollments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_LectureProgresses_Lectures_LectureId" FOREIGN KEY ("LectureId") REFERENCES "Lectures" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Questions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuizId" integer NOT NULL,
        "Text" text NOT NULL,
        "Type" integer NOT NULL,
        "Points" integer NOT NULL,
        "OrderIndex" integer NOT NULL,
        CONSTRAINT "PK_Questions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Questions_Quizzes_QuizId" FOREIGN KEY ("QuizId") REFERENCES "Quizzes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "QuizAttempts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "EnrollmentId" integer NOT NULL,
        "QuizId" integer NOT NULL,
        "Score" integer NOT NULL,
        "IsPassed" boolean NOT NULL,
        "AttemptedAt" timestamp with time zone NOT NULL,
        "CompletedAt" timestamp with time zone,
        CONSTRAINT "PK_QuizAttempts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QuizAttempts_Enrollments_EnrollmentId" FOREIGN KEY ("EnrollmentId") REFERENCES "Enrollments" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_QuizAttempts_Quizzes_QuizId" FOREIGN KEY ("QuizId") REFERENCES "Quizzes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE TABLE "Answers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "QuestionId" integer NOT NULL,
        "Text" text NOT NULL,
        "IsCorrect" boolean NOT NULL,
        "OrderIndex" integer NOT NULL,
        CONSTRAINT "PK_Answers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Answers_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES "Questions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Answers_QuestionId" ON "Answers" ("QuestionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Categories_ParentCategoryId" ON "Categories" ("ParentCategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Certificates_CertificateNumber" ON "Certificates" ("CertificateNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Certificates_EnrollmentId" ON "Certificates" ("EnrollmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Courses_CategoryId" ON "Courses" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Courses_LecturerId" ON "Courses" ("LecturerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Enrollments_CourseId" ON "Enrollments" ("CourseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Enrollments_StudentId" ON "Enrollments" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_LectureProgresses_EnrollmentId" ON "LectureProgresses" ("EnrollmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_LectureProgresses_LectureId" ON "LectureProgresses" ("LectureId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Lectures_ModuleId" ON "Lectures" ("ModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Modules_CourseId" ON "Modules" ("CourseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Payments_EnrollmentId" ON "Payments" ("EnrollmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Questions_QuizId" ON "Questions" ("QuizId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_QuizAttempts_EnrollmentId" ON "QuizAttempts" ("EnrollmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_QuizAttempts_QuizId" ON "QuizAttempts" ("QuizId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Quizzes_ModuleId" ON "Quizzes" ("ModuleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Reviews_CourseId" ON "Reviews" ("CourseId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE INDEX "IX_Reviews_StudentId" ON "Reviews" ("StudentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260327205513_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260327205513_InitialCreate', '10.0.5');
    END IF;
END $EF$;
COMMIT;

